package com.zonal.starwars;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zonal.starwars.model.Planet;

import com.zonal.starwars.PlanetDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig planetDaoConfig;

    private final PlanetDao planetDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        planetDaoConfig = daoConfigMap.get(PlanetDao.class).clone();
        planetDaoConfig.initIdentityScope(type);

        planetDao = new PlanetDao(planetDaoConfig, this);

        registerDao(Planet.class, planetDao);
    }
    
    public void clear() {
        planetDaoConfig.clearIdentityScope();
    }

    public PlanetDao getPlanetDao() {
        return planetDao;
    }

}
